# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('finGrade', models.CharField(max_length=10)),
                ('currentRev', models.FloatField(default=0)),
                ('profit', models.FloatField(default=0)),
            ],
        ),
    ]
