# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TradeNet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OwnedStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5)),
                ('lastPrice', models.FloatField(default=0)),
                ('exchange', models.FloatField(default=0)),
                ('dailyNetChange', models.FloatField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TradeNet.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('time', models.DateTimeField(verbose_name='time of transaction')),
                ('quantity', models.IntegerField(default=1)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TradeNet.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('balance', models.FloatField(default=0.0)),
                ('profit', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='ownedstock',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TradeNet.Stock'),
        ),
        migrations.AddField(
            model_name='ownedstock',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TradeNet.User'),
        ),
        migrations.AddField(
            model_name='history',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TradeNet.Transaction'),
        ),
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TradeNet.User'),
        ),
    ]
