# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TradeNet', '0002_auto_20161202_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='email',
        ),
        migrations.AddField(
            model_name='ownedstock',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='transaction',
            name='buy',
            field=models.BooleanField(default=True),
        ),
    ]
