# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TradeNet', '0003_auto_20161203_1027'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserBalance',
        ),
    ]
