# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 22:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TradeNet', '0004_auto_20161203_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownedstock',
            name='transaction',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='TradeNet.Transaction'),
            preserve_default=False,
        ),
    ]
