# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TradeNet', '0007_auto_20161205_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='exchange',
            field=models.CharField(default=5, max_length=200),
        ),
    ]
